imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.mongodb
        name: rapid_transit_main
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Additional Bundles

sylius_resource:
    resources:
        transit.user_account:
            driver: doctrine/mongodb-odm
            classes:
                model: Transit\WebBundle\Model\UserAccount
                controller: Transit\WebBundle\Controller\UserAccountController
                repository: Transit\WebBundle\Repository\UserAccountRepository
        transit.oauth_account:
            driver: doctrine/mongodb-odm
            classes:
                model: Transit\WebBundle\Model\OauthAccount
                controller: Transit\WebBundle\Controller\OauthAccountController
                repository: Transit\WebBundle\Repository\OauthAccountRepository

ornicar_gravatar: ~

stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            timestampable: true
            blameable: true

jms_i18n_routing:
    default_locale: "%locale%"
    locales: [ en ]
    strategy: prefix
    cookie:
        name: rapid_transit_locale

