imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.mongodb
        name: rapid_transit_main
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   "%database_driver%"
#        host:     "%database_host%"
#        port:     "%database_port%"
#        dbname:   "%database_name%"
#        user:     "%database_user%"
#        password: "%database_password%"
#        charset:  UTF8
#        # if using pdo_sqlite as your database driver:
#        #   1. add the path in parameters.yml
#        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#        #   2. Uncomment database_path in parameters.yml.dist
#        #   3. Uncomment next line:
#        #     path:     "%database_path%"
#
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        auto_mapping: true



doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}

    default_database: "%mongodb_database%_%kernel.environment%"

    document_managers:
        default:
            auto_mapping: true

services:
    doctrine:
        alias: doctrine_mongodb

#######

sylius_resource:
    resources:
        transit.user:
            driver: doctrine/mongodb-odm
            classes:
                model: Transit\WebBundle\Model\User
                controller: Transit\WebBundle\Controller\UserController
                repository: Transit\WebBundle\Doctrine\ORM\UserRepository

ornicar_gravatar: ~

stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
            timestampable: true
            blameable: true
