parameters:
    mongodb.session.options:
        database: "%mongodb_database%_%kernel.environment%"
        collection: TransitSession

services:
    session.handler.mongodb:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments:
            - "@mongo"
            - "%mongodb.session.options%"

    mongodb.connection:
        class: Doctrine\MongoDB\Connection
        factory_service: doctrine.odm.mongodb.document_manager
        factory_method: getConnection
        calls:
           - [initialize, []]

    mongo:
        class: Mongo
        factory_service: mongodb.connection
        factory_method: getMongo
